### PR TITLE
Add GitHub Actions

### PR DESCRIPTION
**Pull request by jv-asana**
- Added GitHub Actions workflow for building and testing on different versions of Python
- Added GitHub Actions workflow for GitHub Releases
- Added GitHub Actions workflow for PyPI and Test PyPI

### CODE REVIEW

**Review by mlee-asana — APPROVED** [review]
looks good to me - I'm not super familiar with the config requirements for github workflows but it's probably relatively low risk to iterate here in case there's something misconfigured - guessing the worst thing that could happen is a failure to publish?

**Comment by mlee-asana** [comment]
also one thing I wanted to flag - it seems bad that the travis PW was stored in plaintext in code. at a minimum we should rotate that out now that it's stored in secrets

**Comment by jv-asana** [comment]
> looks good to me - I'm not super familiar with the config requirements for github workflows but it's probably relatively low risk to iterate here in case there's something misconfigured - guessing the worst thing that could happen is a failure to publish?

Yeah worst case is that one of the release methods fails to publish and we have to re-run the workflow again hence one of the reasons why I separated GitHub Releases and PyPI release into their own workflows.

**Comment by mlee-asana** [comment]
ah ok nvm then - thought it was the actual API key, which would be bad haha

**Comment by jv-asana** [comment]
> ah ok nvm then - thought it was the actual API key, which would be bad haha

Yeah thought the same until I read the docs. You encrypt it with Travis CI CLI command and Travis CI will decrypt it when it runs.

**Review by aw-asana — APPROVED** [review]
LGTM

**Pull request merged**
