### PR TITLE
Update dependencies.

### LINKED ISSUE #33: Update requests_oauthlib from 0.5.0 -> 0.6.1
There are a few bug fixes, including issue https://github.com/requests/requests-oauthlib/issues/211 which breaks the authorization workflow using the python API.

Will still need to make new distributions on PyPI in order for pip to pull these down.

### PR DESCRIPTION
**Pull request by theaeolianmachine**
* Use explicit compatible versions.
* Make sure to upgrade requests_oauthlib because of #33.
* Fixes #33.

### CODE REVIEW

**Comment by theaeolianmachine** [comment]
Will need to look into tests soon (might have broken with newer version of py.test, though it wasn't versioned beforehand).

**Comment by agnoster** [comment]
If the tests are breaking, might it be worth updating dependencies other than pytest separately?

**Comment by theaeolianmachine** [comment]
It's nothing to do with that - it's because this block:
```
# From https://github.com/dropbox/responses/issues/31#issuecomment-63165210
from inspect import getmembers, isfunction, ismethod
def decallmethods(decorator, prefix='test_'):
    def dectheclass(cls):
        for name, m in getmembers(cls, predicate=lambda x: isfunction(x) or ismethod(x)):
            if name.startswith(prefix):
                setattr(cls, name, decorator(m))
        return cls
    return dectheclass
```

Isn't working in python 2.7 (because each member is an unbound method instead of a function in python 3 - I'm assuming we just missed this happening beforehand?). Essentially the tests won't work even when run as standard unittests - looking into a solution...

**Comment by theaeolianmachine** [comment]
Heh, funny the comment it referenced shows that the solution doesn't work in python 2, and it's ongoing:
https://github.com/getsentry/responses/issues/31

With a fix as of 2 weeks ago. Will try it out and open another PR.

**Comment by theaeolianmachine** [comment]
@agnoster, if everything in #39 looks good, then I can re-run the build here and it's all up for you from here.

**Pull request merged**
